### ISSUE TITLE
能提供下初赛数据集供学习使用吗？

### ISSUE THREAD

**Issue by gdtydm** [jiuxianghedonglu/MMC-TOP40-Solution#2]
能提供下初赛数据集供学习使用吗？
我没参加比赛 拿不到数据集，希望你提供一下，非常感谢。961213106@qq.com

**Comment by jiuxianghedonglu** [comment]
> 能提供下初赛数据集供学习使用吗？
> 我没参加比赛 拿不到数据集，希望你提供一下，非常感谢。[961213106@qq.com](mailto:961213106@qq.com)

链接：https://pan.baidu.com/s/1OI08R_KqCd_SYNCk3ymCDA 
提取码：bw3u

**Comment by Aifcce** [comment]
谢谢啦。真的很感谢

**Comment by gdtydm** [comment]
> > 能提供下初赛数据集供学习使用吗？
> > 我没参加比赛 拿不到数据集，希望你提供一下，非常感谢。[961213106@qq.com](mailto:961213106@qq.com)
> 
> 链接：https://pan.baidu.com/s/1OI08R_KqCd_SYNCk3ymCDA
> 提取码：bw3u

谢谢啦。真的很感谢
